name = "prova-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Uncomment if you need KV storage
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"
